### ISSUE TITLE
Exact Query?

### ISSUE THREAD

**Issue by aramrw** [vincent-herlemont/native_db#201]
### Enable querying database via an exact match.

I'm 90% sure I am missing something and it already exists, so if it does it would be much appreciated to show how I could do an exact match 👍🏼 .
However I will explain why it could be important if it really does not exist yet.

native_db is perfect for a dictionary because of it's features, however right now I'm using `start_with` but I would like to add that as a setting, not the default. 

For example, if you look up `読み`, its going to search for `読み*`, resulting in 
1. 読み
2. 読み方
3. 読み上げる
4. 読み書き
5. 読み物
6. 読みにくい

This could potentially not only be very slow, but also just flood the results with a ton of maybe unwanted terms, in my case if I had _10_ different dictionaries, this would result in _60_ definitions, where as I would only like 10 definitions, matching `読み` only. 

I only listed out 6 results, but there could be maybe 100+ more of these _per dictionary_, it would slower than necessary, so the simple answer of just filtering _after_ the query wouldn't really be the best option for me, as performance is the #1 priority.

As for `range`, jp for example has no spaces, and requires custom logic with graphemes to parse, requiring a lot more custom logic. I'm just wondering since redb has the exact match if maybe native_db could also add it? it would be much appreciated. 

#### What I am doing currently
```rust
fn query_sw<'a>(
    rtx: &RTransaction,
    key: DatabaseTermEntryKey,
    query: impl ToKey + 'a,
) -> Result<Vec<DatabaseTermEntry>, DBError> {
    Ok(rtx
        .scan()
        .secondary(key)?
        // "読み"
        .start_with(query)
        // ✓: 読み 
        // 𐄂: 読み方, 読み上げる, 読み書き, 読み物, 読みにくい...more 
        .collect::<Result<Vec<DatabaseTermEntry>, db_type::Error>>()?)
}
```
#### Exact query
```rust
fn query_exact<'a>(
    rtx: &RTransaction,
    key: DatabaseTermEntryKey,
    query: impl ToKey + 'a,
) -> Result<Vec<DatabaseTermEntry>, DBError> {
    Ok(rtx
        .scan()
        .secondary(key)?
        // "読み"
        .exact(query)
        // only matches "読み"
        .collect::<Result<Vec<DatabaseTermEntry>, db_type::Error>>()?)
}
```

**Comment by aramrw** [comment]
I just realized I was using `scan` instead of `get`...My fault 🤣 

keep up the great work bro 👍🏼

**Comment by aramrw** [comment]
Actually I just remembered why I couldn't do that, you _have_ to use scan if they are not unique..My bad, I'm still looking for a way to do the exact search

**Comment by vincent-herlemont** [comment]
It is true that there is no exact match, and the way the indexes are implemented does not allow for an exact match on an optional key unless you go through the possibilities with a prefix as you did (whether you or Native DB do it, the performance will be the same).

However, an optimized solution exists! Since your key is a string of characters, the keys are stored in ascending order, so "読み" > "読み方" > "読み上げる", etc. (verify this in case you have a custom key [[1](https://docs.rs/native_db/latest/native_db/db_type/trait.ToKey.html),[2](https://docs.rs/native_db/latest/native_db/struct.Models.html#define-a-model-with-a-secondary-key-and-a-custom-secondary-key-optional)]). In this case, you can use an iterator like [`take_while`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.take_while) so the database will only iterate over the n elements corresponding to your match.

**Comment by aramrw** [comment]
> In this case, you can use an iterator like [`take_while`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.take_while) so the database will only iterate over the n elements corresponding to your match.

Exact what I needed thanks a lot 👍🏼 keep up the great work bro 🦾

**Comment by C4Phoenix** [comment]
I'm having the same problem and I wanted to note that a good 'hack' could be too just call range like with an inclusive range like so:

```rust
fn query_exact<'a>(
    rtx: &RTransaction,
    key: DatabaseTermEntryKey,
    query: impl ToKey + 'a,
) -> Result<Vec<DatabaseTermEntry>, DBError> {
    Ok(rtx
        .scan()
        .secondary(key)?
        // "読み"
        .range(query..=query)
        // only matches "読み"
        .collect::<Result<Vec<DatabaseTermEntry>, db_type::Error>>()?)
}
```
This worked for my limited testing. The api could also easily implement a exact method the same way it did start_with to make it a bit cleaner.
