### ISSUE TITLE
Scan order on custom keys differs between String and chrono::DateTime ?

### ISSUE THREAD

**Issue by lbarnkow** [vincent-herlemont/native_db#206]
First of all: A huge thank you for providing native_db and native_model! So far it has been a fantastic embedded database for my personal project! :heart: 

It seems to me that the sort order for `scan().secondary().all()` is different between `String` and `chrono::DateTime`? Initially I was under the impression that both primary and secondary index scans should yield keys in ascending order. However, this minimal example doesn't work the way I expected it. _(Note that the entries are inserted with decreasing primary index `u64` values.)_

Cargo.toml
```
[package]
name = "native_db_chrono_test"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
#serde_json = "1.0.68"

native_db = { version = "0.7.1", features = ["chrono"] }
native_db_macro = "0.7.1"
native_model = "0.4.19"

chrono = { version = "0.4.38" , features = ["serde"] }
```

main.rs
```
use native_db::*;
use native_model::{native_model, Model};
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
#[native_db]
#[native_model(id = 1, version = 1)]
struct DataChrono {
    #[primary_key]
    id: u64,
    #[secondary_key]
    timestamp: chrono::DateTime<chrono::Local>,
}

impl DataChrono {
    fn new(id: u64) -> Self {
        Self { id, timestamp: chrono::Local::now() }
    }
}

#[derive(Debug, Serialize, Deserialize)]
#[native_db]
#[native_model(id = 2, version = 1)]
struct DataString {
    #[primary_key]
    id: u64,
    #[secondary_key]
    timestamp: String,
}

impl DataString {
    fn new(id: u64) -> Self {
        Self { id, timestamp: chrono::Local::now().to_rfc3339() }
    }
}

fn main() {
    let mut models = Models::new();
    models.define::<DataChrono>().unwrap();
    models.define::<DataString>().unwrap();

    let db = Builder::new().create_in_memory(&models).unwrap();

    let tx = db.rw_transaction().unwrap();
    for i in (0..10).rev() {
        tx.insert(DataChrono::new(i)).unwrap();
        tx.insert(DataString::new(i)).unwrap();
    }
    tx.commit().unwrap();

    let tx = db.r_transaction().unwrap();
    println!("DateTime as secondary key:\n==========================");
    for entry in tx.scan().secondary::<DataChrono>(DataChronoKey::timestamp).unwrap().all() {
        println!("{entry:?}");
    }
    println!("\nString as secondary key:\n========================");
    for entry in tx.scan().secondary::<DataString>(DataStringKey::timestamp).unwrap().all() {
        println!("{entry:?}");
    }
}
```

Output:
```
$ cargo run
   Compiling native_db_chrono_test v0.1.0 (/home/wsluser/workspaces/local/native_db_chrono_test)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.28s
     Running `target/debug/native_db_chrono_test`
DateTime as secondary key:
==========================
Ok(DataChrono { id: 0, timestamp: 2024-08-02T21:54:38.026388021+02:00 })
Ok(DataChrono { id: 1, timestamp: 2024-08-02T21:54:38.026338285+02:00 })
Ok(DataChrono { id: 2, timestamp: 2024-08-02T21:54:38.026290339+02:00 })
Ok(DataChrono { id: 3, timestamp: 2024-08-02T21:54:38.026242928+02:00 })
Ok(DataChrono { id: 4, timestamp: 2024-08-02T21:54:38.026196318+02:00 })
Ok(DataChrono { id: 5, timestamp: 2024-08-02T21:54:38.026149291+02:00 })
Ok(DataChrono { id: 6, timestamp: 2024-08-02T21:54:38.026104080+02:00 })
Ok(DataChrono { id: 7, timestamp: 2024-08-02T21:54:38.026058670+02:00 })
Ok(DataChrono { id: 8, timestamp: 2024-08-02T21:54:38.026005737+02:00 })
Ok(DataChrono { id: 9, timestamp: 2024-08-02T21:54:38.025755997+02:00 })

String as secondary key:
========================
Ok(DataString { id: 9, timestamp: "2024-08-02T21:54:38.025931735+02:00" })
Ok(DataString { id: 8, timestamp: "2024-08-02T21:54:38.026035696+02:00" })
Ok(DataString { id: 7, timestamp: "2024-08-02T21:54:38.026082222+02:00" })
Ok(DataString { id: 6, timestamp: "2024-08-02T21:54:38.026127051+02:00" })
Ok(DataString { id: 5, timestamp: "2024-08-02T21:54:38.026173730+02:00" })
Ok(DataString { id: 4, timestamp: "2024-08-02T21:54:38.026220179+02:00" })
Ok(DataString { id: 3, timestamp: "2024-08-02T21:54:38.026267193+02:00" })
Ok(DataString { id: 2, timestamp: "2024-08-02T21:54:38.026314768+02:00" })
Ok(DataString { id: 1, timestamp: "2024-08-02T21:54:38.026363817+02:00" })
Ok(DataString { id: 0, timestamp: "2024-08-02T21:54:38.026413559+02:00" })
```

Scanning a `String` secondary index (lower output) yields all entries in ascending lexicographical order as expected, i.e. the first inserted entry has the lowest timestamp and is therefore printed first.

Scanning a `chrono::DateTime` secondary index (upper output) yields the entries in a different order. DateTime seems to implement `PartialOrd`/`Ord` which had me confused. While in this demo the order is just reversed but seemingly deterministic, in a more complex program where I first encountered the unexpected ordering it looked more random.

Do you have any insights as to why `chrono::DateTime` secondary keys behave this way?
If this is expected behavior, please consider adding some documentation about index ordering.

**Comment by vincent-herlemont** [comment]
@lbarnkow Thank you for pointing that out, this is an issue. 

This is because the data of `chrono::DateTime` are stored in the database using the [DateTime.timestamp](https://docs.rs/chrono/latest/chrono/struct.DateTime.html#method.timestamp) function, which returns the UNIX standard:

> Returns the number of non-leap seconds since January 1, 1970 0:00:00 UTC (aka “UNIX timestamp”).

This is a problem in your case because, as there is no wait time in your loop, the precision should be in nanoseconds. In your case, the data is inserted in the same second, so the order of insertion prevails.

Try to wait 1 second between each insert and you should have the good result.
```rust
...
for i in (0..10).rev() {
    std::thread::sleep(std::time::Duration::from_secs(1));
    tx.insert(DataChrono::new(i)).unwrap();
    tx.insert(DataString::new(i)).unwrap();
}
...
```

It might be necessary to change this by using [DateTime.timestamp_nanos](https://docs.rs/chrono/latest/chrono/struct.DateTime.html#method.timestamp_nanos), but we should consider this carefully because it can panic. Thus, you should check how DateTime is actually stored in other databases.

Here is the code involved [src/db_type/key/key.rs#L283](https://github.com/vincent-herlemont/native_db/blob/c8b892ec40d67ac8ad4404e519ae1a0a14b765a6/src/db_type/key/key.rs#L283).

**Comment by lbarnkow** [comment]
@vincent-herlemont Thanks for pointing out the current implementation of `ToKey` for `DateTime`. I think I'll probably stick to `String` for now.

Unless you want to keep this issue open to track this as a defect I guess this can be closed now as there is no easy fix.

**Comment by vincent-herlemont** [comment]
I think I'll probably stick to `String` for now.

👍 

> Unless you want to keep this issue open to track this as a defect I guess this can be closed now as there is no easy fix.

Hmm, I think you can leave it open. I will try to fix this as soon as possible, whether it's through documentation or implementation.

---

I was able to see in the following documentation:

- PostgreSQL [doc](https://www.postgresql.org/docs/current/datatype-datetime.html) uses microseconds.
- Oracle [doc](https://docs.oracle.com/en/database/oracle/oracle-database/23/odpnt/TimeStampProperties.html#GUID-B895665E-9F53-4F02-8C04-3A78E53287FB) uses nanoseconds.
- SQLite [doc](https://www.sqlite.org/lang_datefunc.html) uses dynamic typing.
- MongoDB [doc](https://www.mongodb.com/docs/manual/reference/bson-types/#date) uses microseconds.
- SurrealDB [doc](https://surrealdb.com/docs/surrealdb/surrealql/datamodel/datetimes) uses nanoseconds (maybe the implementation in question [/core/src/fnc/time.rs#L151](https://github.com/surrealdb/surrealdb/blob/27e17d7cdd37411b3646d3bfed339ff5f18e4651/core/src/fnc/time.rs#L151))

It seems to me that storing in microseconds seems acceptable, but maybe nanoseconds too. I'm hesitant... @lbarnkow have you an opinion about that?

And also thinking about the migration.

**Comment by lbarnkow** [comment]
First of: I have been learning Rust for maybe 2 years now and feel I have no real world experience as I only use it in personal projects not professionally. Keep that in mind when reading on. :smile: 

I believe the built-in support for chrono (and uuid) is well intentioned (as other database offer native support for datetime/timestamp types), but maybe should not be part of the core crate? Having `chrono::DateTime` with nanosecond precision stored in the database but implicitly being keyed / indexed with any other precision is confusing to an end user, I think. If it were to stay this way, we would need documentation explicitly calling out this behavior or at least a comment in the custom-type test for chrono, from which I originally took inspiration.

For my own project I wrote a wrapper struct around `chrono::DateTime` implementing `From<chrono::DateTime>` and `Deref`, so it's easy to convert any `chrono::DateTime<Tz>` to my wrapper with `.into()` and still have all `chrono::DateTime` methods available. Using your `ToKey` implementation as base I opted to conserve the full nanosecond precision as the limited value range is more than sufficient for my app. See https://gist.github.com/lbarnkow/1d556cffbd1318e8df1a82be6d67fb06. 

Maybe in the future you could provide an additional crate `native_db_chrono` that offers two such wrapper types? One that offers nano second precision as seen in my gist with the caveat of a panic if the value is out of the value range that `timestamp_nanos_opt` supports (`1677-09-21T00:12:43.145224192` and `2262-04-11T23:47:16.854775807`). And another wrapper that offers microsecond precision which (judging by the chrono docs) should support the full range (_"Date types are limited to about +/- 262,000 years from the common epoch."_). Then native_db could deprecate the `chrono` feature and force users to update their models to one of the wrappers doing proper model versioning and migrations?

**Comment by vincent-herlemont** [comment]
@lbarnkow Thank you for your advice and feedback, it's valuable!

Indeed, leave users to use their own UUID and chrono wrappers would indeed be a good idea, and thus document how to implement them with `ToKey`.
