### ISSUE TITLE
Remove skeptic and find an alternative

### ISSUE THREAD

**Issue by vincent-herlemont** [vincent-herlemont/native_db#250]
The `skeptic` crate, which is used to execute the code in the readme, is no longer supported. Therefore, it needs to be removed and an alternative solution found. (The crate does not work with Rust versions higher than 1.77, see https://github.com/budziq/rust-skeptic/issues/141).

One possible solution could be to include the readme in the Rust documentation via [`#[doc = include_str!("../../README.md")]
`](https://doc.rust-lang.org/rustdoc/write-documentation/the-doc-attribute.html).

# TODO
- [x] Investigate
- [x] Implement

**Comment by ubaldop** [comment]
A PR removing the dependency is [here](https://github.com/vincent-herlemont/native_db/pull/286).
