### ISSUE TITLE
Request to Add Polly Scheduler as a Recommended Example Project

### ISSUE THREAD

**Issue by dongbin86** [vincent-herlemont/native_db#262]
I am currently using NativeDB as the storage backend for my task scheduling [system.](https://github.com/dongbin86/polly-scheduler) I have been very pleased with its performance and capabilities.

I would like to request that you consider adding Polly Scheduler as a recommended example project on the NativeDB documentation page. I believe that it could serve as a valuable reference for other users who are looking to implement task scheduling systems with NativeDB.

I would like to ask a question regarding the differences between supporting update and insert operations. It seems that for an update, I need to first retrieve the entity, modify it, and then perform the update. Can I directly overwrite it using insert instead?

Also, for delete operations, does it only require creating a default entity with just the primary key set, without worrying about the other fields?

**Comment by vincent-herlemont** [comment]
@dongbin86 thank you for your message!

> I would like to request that you consider adding Polly Scheduler as a recommended example project on the NativeDB documentation page.

Why not! I let you create a pull request to add a section "Projects Using Native DB" after the section "How to use?" and your project inside.

> I would like to ask a question regarding the differences between supporting update and insert operations. It seems that for an update, I need to first retrieve the entity, modify it, and then perform the update. Can I directly overwrite it using insert instead?
> 
> Also, for delete operations, does it only require creating a default entity with just the primary key set, without worrying about the other fields?

Could you open a discussion for each question here: [native_db/discussions](https://github.com/vincent-herlemont/native_db/discussions). This will allow me to respond clearly to each of your requests.

**Comment by dongbin86** [comment]
@vincent-herlemont thanks, https://github.com/vincent-herlemont/native_db/pull/263, https://github.com/vincent-herlemont/native_db/discussions/264

**Comment by vincent-herlemont** [comment]
@dongbin86 If this issue is resolved, I'll let you close this issue.
