### ISSUE TITLE
Implement IndexDB Support

### ISSUE THREAD

**Issue by vincent-herlemont** [vincent-herlemont/native_db#34]
After thorough consideration and analysis, we have decided not to implement support for IndexDB in the Struct DB project at this stage. This decision is based on the following reasons:

1. **No Immediate Need**: The database is primarily designed for cross-platform Mobile/Desktop applications, and there is no immediate requirement for execution in the browser in offline mode.
2. **Significant Refactoring Required**: Implementing IndexDB would require a substantial refactor of the existing codebase, which is not justifiable at this stage of development.
3. **Focus on Other Platforms**: The primary focus of Struct DB is to provide a drop-in, fast, and embedded database solution for Linux, macOS, Windows, Android, and iOS. The inclusion of browser-based WebBrowser WASM support is not aligned with the current goals.

However, we acknowledge that there may be potential use cases for IndexDB support in the future. Therefore, we will keep this issue open and invite community feedback and discussion.

**Comment by GregoryConrad** [comment]
If your goal is to get browser support, here’s my two cents: redb supports wasi (I was actually the one who contributed wasi support to redb), so you could get browser support in native db via wasi as a compilation target in conjunction with a WASI-JS polyfill like wasmer.js (see https://github.com/wasmerio/wasmer-js/issues/305)

**Comment by vincent-herlemont** [comment]
> GregoryConrad

Thank you for your comment. I have just opened a specific issue https://github.com/vincent-herlemont/native_db/issues/65 for this, and I will close this one as it is no longer relevant.
