### ISSUE TITLE
create_temp should use a scoped tempfile

### ISSUE THREAD

**Issue by poelzi** [vincent-herlemont/native_db#54]
I think it would be better if `Builder::new()::create_temp()` would return a Database that uses a [tempfile](https://docs.rs/tempfile/latest/tempfile/) to create a file backed Database, but drops the file once the Database is dropped.

On Linux at least, a file can be created and instantly unlink. As long as one file descriptor is open, the file remains and gets cleaned after last usage.

I think create_temp should be used for tests only, and the current behavior is not really deterministic which easily makes you search bugs that do not exist

**Comment by vincent-herlemont** [comment]
You're right; it's misleading. 

I'm questioning the very usefulness of this method. Maybe we should just remove it and let the test decide whether to use the tempfile crate or another mechanism to manage the lifecycle of temporary files. @poelzi What's your opinion on this?

**Comment by vincent-herlemont** [comment]
@poelzi The API has been rewritten and there is no longer a `create_temp`. Please don't hesitate to let me know if you notice anything else odd :)
