### ISSUE TITLE
Support no-std

### ISSUE THREAD

**Issue by vincent-herlemont** [vincent-herlemont/native_db#66]
- [ ] Explore different ways
- [ ] Fix various issues.

**Comment by AlvinKuruvilla** [comment]
This is a cool project, and I'm considering contributing however I can. In regards to this, I see a couple of blockers specifically. 
 - Tokio (to my knowledge) does not have ```no_std``` support
 - native_model: Brings in the ```Result```  type

**Comment by vincent-herlemont** [comment]
Thank you, @AlvinKuruvilla, for your interest in this project. You are absolutely right; there are several bottlenecks to supporting `no-std`, and I'm not sure if it's feasible. In addition to Tokio/`Results` and other necessary refactoring to make the Native DB code no-std compatible, there's [redb](https://github.com/cberner/redb) (used as a backend) which seems not to support no-std either. So, it doesn't look very promising in this regard... If you have any other advice or suggestions, please don't hesitate to share.

**Comment by AlvinKuruvilla** [comment]
After researching, I found that the best database backend candidate I could find is [jammdb](https://github.com/pjtatlow/jammdb). I don't know how compatible it is with the current API/types, but it seems like a good option with the limited options. If there's anything you would rather me prioritize working on (it doesn't even need to be on this), I'd be more than happy to take a stab at it.

**Comment by vincent-herlemont** [comment]
For now, no-std is not the priority for this database and is somewhat out of scope. I am closing this issue. If anyone is interested in working on this issue, you are welcome to comment and reopen it.
